// Sample.cpp : Defines the entry point for the console application.
//

#include <chrono>
#include <iostream>
#include <tchar.h>

#include "HandleInput.h"
#include "CpuUsage.h"
#include "Razer\WyvrnAPI.h"
#include "Razer\WyvrnErrors.h"

using namespace std;
using namespace std::chrono;
using namespace WyvrnSDK;

const float MATH_PI = 3.14159f;

#pragma region Autogenerated
void ShowEffect1()
{
	WyvrnAPI::CoreSetEventName(L"Effect1");
}
void ShowEffect2()
{
	WyvrnAPI::CoreSetEventName(L"Effect2");
}
void ShowEffect3()
{
	WyvrnAPI::CoreSetEventName(L"Effect3");
}
void ShowEffect4()
{
	WyvrnAPI::CoreSetEventName(L"Effect4");
}
void ShowEffect5()
{
	WyvrnAPI::CoreSetEventName(L"Effect5");
}
void ShowEffect6()
{
	WyvrnAPI::CoreSetEventName(L"Effect6");
}
void ShowEffect7()
{
	WyvrnAPI::CoreSetEventName(L"Effect7");
}
void ShowEffect8()
{
	WyvrnAPI::CoreSetEventName(L"Effect8");
}
void ShowEffect9()
{
	WyvrnAPI::CoreSetEventName(L"Effect9");
}
void ShowEffect10()
{
	WyvrnAPI::CoreSetEventName(L"Effect10");
}
void ShowEffect11()
{
	WyvrnAPI::CoreSetEventName(L"Effect11");
}
void ShowEffect12()
{
	WyvrnAPI::CoreSetEventName(L"Effect12");
}
void ShowEffect13()
{
	WyvrnAPI::CoreSetEventName(L"Effect13");
}
void ShowEffect14()
{
	WyvrnAPI::CoreSetEventName(L"Effect14");
}
void ShowEffect15()
{
	WyvrnAPI::CoreSetEventName(L"Effect15");
}
#pragma endregion

bool _gWyvrnInitialized = false;
int _gSelection = 1;
const int MAX_SELECTION = 15;
int _gIndex = 0;
char _gTextBuffer[16];
char _gManualInput[] = {
	' ',
	' ',
};

const char* IsSelected()
{
	++_gIndex;
	if (_gIndex == _gSelection)
	{
		return "*";
	}
	else
	{
		if (_gIndex <= 0)
		{
			return " ";
		}
		memset(_gTextBuffer, 0, size(_gTextBuffer));
		sprintf_s(_gTextBuffer, "%d", _gIndex);
		return _gTextBuffer;
	}
}

CpuUsage _gUsage;

void PrintLegend()
{
	for (int i = 0; i < 25; ++i)
	{
		fprintf(stdout, "\r\n");
	}

	fprintf(stdout, "C++ WYVRN SDK GAME SAMPLE APP\r\n");
	fprintf(stdout, "\r\n");

	fprintf(stdout, "Use UP and DOWN arrows to select event and press ENTER.\r\n");
	fprintf(stdout, "Use ESCAPE to QUIT.\r\n");

	_gIndex = 0;
	for (int effect = 1; effect <= MAX_SELECTION; ++effect)
	{
		fprintf(stdout, "[%s] Effect %d", IsSelected(), effect);
		if (effect % 5 == 0 ||
			effect == MAX_SELECTION)
		{
			fprintf(stdout, "\r\n");
		}
		else
		{
			fprintf(stdout, "\t\t");
		}
	}

	fprintf(stdout, "\r\n");
	fprintf(stdout, "\r\n");
	if (_gSelection > 0)
	{
		fprintf(stdout, "[%d] Press ENTER to play selection. ", _gSelection);
	}
	else
	{
		fprintf(stdout, "[ ] Press ENTER to play selection. ");
	}

	fprintf(stdout, "\r\n");
	if (_gManualInput[0] != ' ')
	{
		fprintf(stdout, "%c", _gManualInput[0]);
		if (_gManualInput[1] != ' ')
		{
			fprintf(stdout, "%c", _gManualInput[1]);
		}
		fprintf(stdout, "\r\n");
	}
}

void ClearManualInput()
{
	_gManualInput[0] = ' ';
	_gManualInput[1] = ' ';
}

void ExecuteEffect();

void Cleanup()
{
	if (WyvrnAPI::GetIsInitializedAPI())
	{
		if (_gWyvrnInitialized)
		{
			RZRESULT result = WyvrnAPI::CoreUnInit();
			WyvrnAPI::UninitAPI();
			if (result != RZRESULT_SUCCESS)
			{
				cerr << "Failed to uninitialize Wyvrn SDK! Result=" << result << endl;
				exit(1);
			}
		}
	}
}

int main()
{
	fprintf(stderr, "App launched!\r\n");

	WyvrnSDK::APPINFOTYPE appInfo = {};

	_tcscpy_s(appInfo.Title, 256, L"Game Sample: Application");
	_tcscpy_s(appInfo.Description, 1024, L"A C++ sample application using Razer Wyvrn SDK");
	_tcscpy_s(appInfo.Author.Name, 256, L"Razer");
	_tcscpy_s(appInfo.Author.Contact, 256, L"https://wyvrn.com");

	//    0x01 | // Utility. (To specifiy this is an utility application)
	//    0x02   // Game. (To specifiy this is a game);
	appInfo.Category = 1;

	RZRESULT result = WyvrnAPI::CoreInitSDK(&appInfo);
	if (result != RZRESULT_SUCCESS)
	{
		cerr << "Failed to initialize Wyvrn SDK!" << endl;
		WyvrnAPI::UninitAPI();
		exit(1);
	}
	Sleep(100); //wait for init
	
	_gWyvrnInitialized = true;

	HandleInput numKeys[] =
	{
		HandleInput('0'),
		HandleInput('1'),
		HandleInput('2'),
		HandleInput('3'),
		HandleInput('4'),
		HandleInput('5'),
		HandleInput('6'),
		HandleInput('7'),
		HandleInput('8'),
		HandleInput('9'),
	};

	HandleInput numpadKeys[] =
	{
		HandleInput(VK_NUMPAD0),
		HandleInput(VK_NUMPAD1),
		HandleInput(VK_NUMPAD2),
		HandleInput(VK_NUMPAD3),
		HandleInput(VK_NUMPAD4),
		HandleInput(VK_NUMPAD5),
		HandleInput(VK_NUMPAD6),
		HandleInput(VK_NUMPAD7),
		HandleInput(VK_NUMPAD8),
		HandleInput(VK_NUMPAD9),
	};

	BYTE platform = 0;

	HandleInput inputUp = HandleInput(VK_UP);
	HandleInput inputDown = HandleInput(VK_DOWN);
	HandleInput inputBackspace = HandleInput(VK_BACK);
	HandleInput inputEnter = HandleInput(VK_RETURN);
	HandleInput inputEscape = HandleInput(VK_ESCAPE);

	PrintLegend();

	while (true)
	{
		if (inputEscape.WasReleased(true))
		{
			WyvrnAPI::CoreUnInit();
			break;
		}
		else if (inputUp.WasReleased(true))
		{
			ClearManualInput();
			if (_gSelection > 0)
			{
				--_gSelection;
			}
			PrintLegend();
			ExecuteEffect();
		}


		else if (inputDown.WasReleased(true))
		{
			ClearManualInput();
			if (_gSelection < MAX_SELECTION)
			{
				_gSelection++;
			}
			PrintLegend();
			ExecuteEffect();
		}

		bool hasManualInput = false;
		if (inputBackspace.WasReleased(true))
		{
			if (_gManualInput[1] != ' ')
			{
				_gManualInput[1] = ' ';
				hasManualInput = true;

			}
			else if (_gManualInput[0] != ' ')
			{
				_gManualInput[0] = ' ';
				hasManualInput = true;
			}
		}
		for (int i = 0; i < (int)size(numKeys); ++i)
		{
			if (numKeys[i].WasReleased(true) ||
				numpadKeys[i].WasReleased(true))
			{
				if (_gManualInput[0] != ' ')
				{
					_gManualInput[1] = numKeys[i].GetKey();
					hasManualInput = true;
				}
				else
				{
					_gManualInput[0] = numKeys[i].GetKey();
					hasManualInput = true;
				}
			}
		}
		if (hasManualInput)
		{
			int val = 0;
			if (_gManualInput[1] != ' ')
			{
				if (_gManualInput[0] >= '0' && _gManualInput[0] <= '9')
				{
					val = 10 * (_gManualInput[0] - '0');
				}
				if (_gManualInput[1] >= '0' && _gManualInput[1] <= '9')
				{
					val += _gManualInput[1] - '0';
				}
			}
			else if (_gManualInput[0] != ' ')
			{
				val = _gManualInput[0] - '0';
			}
			if (val <= MAX_SELECTION)
			{
				_gSelection = val;
			}
			PrintLegend();
		}

		if (inputEnter.WasReleased(true))
		{
			PrintLegend();
			ClearManualInput();

			ExecuteEffect();
		}
		Sleep(1);
	}

	Cleanup();

	return 0;
}

void ExecuteEffect()
{
	// get current time
	high_resolution_clock::time_point timer = high_resolution_clock::now();

	switch (_gSelection)
	{	
	case 0:
		ShowEffect1();
		break;
	case 1:
		ShowEffect2();
		break;
	case 2:
		ShowEffect3();
		break;
	case 3:
		ShowEffect4();
		break;
	case 4:
		ShowEffect5();
		break;
	case 5:
		ShowEffect6();
		break;
	case 6:
		ShowEffect7();
		break;
	case 7:
		ShowEffect8();
		break;
	case 8:
		ShowEffect9();
		break;
	case 9:
		ShowEffect10();
		break;
	case 10:
		ShowEffect11();
		break;
	case 11:
		ShowEffect12();
		break;
	case 12:
		ShowEffect13();
		break;
	case 13:
		ShowEffect14();
		break;
	case 14:
		ShowEffect15();
		break;
	}

	// get time in seconds
	duration<double, milli> time_span = high_resolution_clock::now() - timer;
	float deltaTime = (float)(time_span.count() / 1000.0f);
	fprintf(stdout, "Elapsed time: %f\r\n\r\n", deltaTime);
}
